server:
  applicationConnectors:
    - type: http
      port: $PORT
  adminConnectors:
    - type: http
      port: 9001

apiConfig:
  aircoachBaseUrl: "https://tracker.aircoach.ie/"
  dublinBusBaseUrl: "http://rtpi.dublinbus.ie/"
  irishRailBaseUrl: "http://api.irishrail.ie/realtime/realtime.asmx/"
  jcDecauxBaseUrl: "https://api.jcdecaux.com/vls/v1/"
  jcDecauxApiKey: ""
  rtpiBaseUrl: "https://rtpiapp.rtpi.openskydata.com/RTPIPublicService_V2/service.svc/"
