server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

apiConfiguration:
  aircoachBaseUrl: "https://tracker.aircoach.ie/"
  dublinBusBaseUrl: "http://rtpi.dublinbus.ie/"
  irishRailBaseUrl: "http://api.irishrail.ie/realtime/realtime.asmx/"
  jcDecauxBaseUrl: "https://api.jcdecaux.com/vls/v1/"
  rtpiBaseUrl: "https://data.smartdublin.ie/cgi-bin/rtpi/"
  rtpiFallbackBaseUrl: "https://rtpiapp.rtpi.openskydata.com/RTPIPublicService_V3/service.svc/"

cacheConfiguration:
  serviceLocationCacheSpec: "refreshAfterWrite=30m,expireAfterWrite=1d"
  liveDataCacheSpec: "refreshAfterWrite=10s,expireAfterWrite=30s"
